set_property SRC_FILE_INFO {cfile:C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_Buttons.xdc rfile:../../../../../src/vhdl/Basys3/Basys3_Buttons.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_Clock.xdc rfile:../../../../../src/vhdl/Basys3/Basys3_Clock.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_LEDs.xdc rfile:../../../../../src/vhdl/Basys3/Basys3_LEDs.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_PS2.xdc rfile:../../../../../src/vhdl/Basys3/Basys3_PS2.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_PmodA.xdc rfile:../../../../../src/vhdl/Basys3/Basys3_PmodA.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_PmodB.xdc rfile:../../../../../src/vhdl/Basys3/Basys3_PmodB.xdc id:6} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_PmodC.xdc rfile:../../../../../src/vhdl/Basys3/Basys3_PmodC.xdc id:7} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_PmodXADC.xdc rfile:../../../../../src/vhdl/Basys3/Basys3_PmodXADC.xdc id:8} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_SegmentDisplay.xdc rfile:../../../../../src/vhdl/Basys3/Basys3_SegmentDisplay.xdc id:9} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_Switches.xdc rfile:../../../../../src/vhdl/Basys3/Basys3_Switches.xdc id:10} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_UART.xdc rfile:../../../../../src/vhdl/Basys3/Basys3_UART.xdc id:11} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_VGA.xdc rfile:../../../../../src/vhdl/Basys3/Basys3_VGA.xdc id:12} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_td_combinatoire.xdc rfile:../../../../../src/vhdl/Basys3/Basys3_td_combinatoire.xdc id:13} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18      [get_ports btn_center_i]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T18      [get_ports btn_up_i]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19      [get_ports btn_left_i]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17      [get_ports btn_right_i]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U17      [get_ports btn_down_i]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5      [get_ports clk_i]
set_property src_info {type:XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {leds_o[0]}]
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports {leds_o[1]}]
set_property src_info {type:XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U19 [get_ports {leds_o[2]}]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19 [get_ports {leds_o[3]}]
set_property src_info {type:XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W18 [get_ports {leds_o[4]}]
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U15 [get_ports {leds_o[5]}]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14 [get_ports {leds_o[6]}]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V14 [get_ports {leds_o[7]}]
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V13 [get_ports {leds_o[8]}]
set_property src_info {type:XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V3  [get_ports {leds_o[9]}]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W3  [get_ports {leds_o[10]}]
set_property src_info {type:XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U3  [get_ports {leds_o[11]}]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3  [get_ports {leds_o[12]}]
set_property src_info {type:XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N3  [get_ports {leds_o[13]}]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P1  [get_ports {leds_o[14]}]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1  [get_ports {leds_o[15]}]
set_property src_info {type:XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports ps2_sclk_io]
set_property src_info {type:XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B17 [get_ports ps2_sdata_io]
set_property src_info {type:XDC file:4 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_*]
set_property src_info {type:XDC file:4 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true         [get_ports ps2_*]
set_property src_info {type:XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports pmod_a1]
set_property src_info {type:XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports pmod_a2]
set_property src_info {type:XDC file:5 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J2 [get_ports pmod_a3]
set_property src_info {type:XDC file:5 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G2 [get_ports pmod_a4]
set_property src_info {type:XDC file:5 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H1 [get_ports pmod_a7]
set_property src_info {type:XDC file:5 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K2 [get_ports pmod_a8]
set_property src_info {type:XDC file:5 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H2 [get_ports pmod_a9]
set_property src_info {type:XDC file:5 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G3 [get_ports pmod_a10]
set_property src_info {type:XDC file:5 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports pmod_a*]
set_property src_info {type:XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports pmod_b1]
set_property src_info {type:XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A16 [get_ports pmod_b2]
set_property src_info {type:XDC file:6 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B15 [get_ports pmod_b3]
set_property src_info {type:XDC file:6 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16 [get_ports pmod_b4]
set_property src_info {type:XDC file:6 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A15 [get_ports pmod_b7]
set_property src_info {type:XDC file:6 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A17 [get_ports pmod_b8]
set_property src_info {type:XDC file:6 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C15 [get_ports pmod_b9]
set_property src_info {type:XDC file:6 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C16 [get_ports pmod_b10]
set_property src_info {type:XDC file:6 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports pmod_b*]
set_property src_info {type:XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports pmod_c1]
set_property src_info {type:XDC file:7 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M18 [get_ports pmod_c2]
set_property src_info {type:XDC file:7 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17 [get_ports pmod_c3]
set_property src_info {type:XDC file:7 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports pmod_c4]
set_property src_info {type:XDC file:7 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L17 [get_ports pmod_c7]
set_property src_info {type:XDC file:7 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M19 [get_ports pmod_c8]
set_property src_info {type:XDC file:7 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P17 [get_ports pmod_c9]
set_property src_info {type:XDC file:7 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports pmod_c10]
set_property src_info {type:XDC file:7 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports pmod_c*]
set_property src_info {type:XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J3 [get_ports pmod_xadc1]
set_property src_info {type:XDC file:8 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L3 [get_ports pmod_xadc2]
set_property src_info {type:XDC file:8 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports pmod_xadc3]
set_property src_info {type:XDC file:8 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N2 [get_ports pmod_xadc4]
set_property src_info {type:XDC file:8 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K3 [get_ports pmod_xadc7]
set_property src_info {type:XDC file:8 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M3 [get_ports pmod_xadc8]
set_property src_info {type:XDC file:8 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M1 [get_ports pmod_xadc9]
set_property src_info {type:XDC file:8 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N1 [get_ports pmod_xadc10]
set_property src_info {type:XDC file:8 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports pmod_xadc*]
set_property src_info {type:XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W7 [get_ports {disp_segments_n_o[0]}]
set_property src_info {type:XDC file:9 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6 [get_ports {disp_segments_n_o[1]}]
set_property src_info {type:XDC file:9 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U8 [get_ports {disp_segments_n_o[2]}]
set_property src_info {type:XDC file:9 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports {disp_segments_n_o[3]}]
set_property src_info {type:XDC file:9 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5 [get_ports {disp_segments_n_o[4]}]
set_property src_info {type:XDC file:9 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports {disp_segments_n_o[5]}]
set_property src_info {type:XDC file:9 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports {disp_segments_n_o[6]}]
set_property src_info {type:XDC file:9 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7      [get_ports disp_point_n_o]
set_property src_info {type:XDC file:9 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports {disp_select_n_o[0]}]
set_property src_info {type:XDC file:9 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports {disp_select_n_o[1]}]
set_property src_info {type:XDC file:9 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports {disp_select_n_o[2]}]
set_property src_info {type:XDC file:9 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W4 [get_ports {disp_select_n_o[3]}]
set_property src_info {type:XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {switches_i[0]}]
set_property src_info {type:XDC file:10 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {switches_i[1]}]
set_property src_info {type:XDC file:10 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {switches_i[2]}]
set_property src_info {type:XDC file:10 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W17 [get_ports {switches_i[3]}]
set_property src_info {type:XDC file:10 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W15 [get_ports {switches_i[4]}]
set_property src_info {type:XDC file:10 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V15 [get_ports {switches_i[5]}]
set_property src_info {type:XDC file:10 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W14 [get_ports {switches_i[6]}]
set_property src_info {type:XDC file:10 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports {switches_i[7]}]
set_property src_info {type:XDC file:10 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2  [get_ports {switches_i[8]}]
set_property src_info {type:XDC file:10 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3  [get_ports {switches_i[9]}]
set_property src_info {type:XDC file:10 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T2  [get_ports {switches_i[10]}]
set_property src_info {type:XDC file:10 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3  [get_ports {switches_i[11]}]
set_property src_info {type:XDC file:10 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W2  [get_ports {switches_i[12]}]
set_property src_info {type:XDC file:10 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1  [get_ports {switches_i[13]}]
set_property src_info {type:XDC file:10 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1  [get_ports {switches_i[14]}]
set_property src_info {type:XDC file:10 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2  [get_ports {switches_i[15]}]
set_property src_info {type:XDC file:11 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18     [get_ports uart_rx_i]
set_property src_info {type:XDC file:11 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_i]
set_property src_info {type:XDC file:11 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18     [get_ports uart_tx_o]
set_property src_info {type:XDC file:11 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_o]
set_property src_info {type:XDC file:12 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G19     [get_ports {vga_red_o[0]}]
set_property src_info {type:XDC file:12 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H19     [get_ports {vga_red_o[1]}]
set_property src_info {type:XDC file:12 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19     [get_ports {vga_red_o[2]}]
set_property src_info {type:XDC file:12 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N19     [get_ports {vga_red_o[3]}]
set_property src_info {type:XDC file:12 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red_o[*]}]
set_property src_info {type:XDC file:12 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18     [get_ports {vga_blue_o[0]}]
set_property src_info {type:XDC file:12 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L18     [get_ports {vga_blue_o[1]}]
set_property src_info {type:XDC file:12 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18     [get_ports {vga_blue_o[2]}]
set_property src_info {type:XDC file:12 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18     [get_ports {vga_blue_o[3]}]
set_property src_info {type:XDC file:12 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue_o[*]}]
set_property src_info {type:XDC file:12 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J17     [get_ports {vga_green_o[0]}]
set_property src_info {type:XDC file:12 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17     [get_ports {vga_green_o[1]}]
set_property src_info {type:XDC file:12 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17     [get_ports {vga_green_o[2]}]
set_property src_info {type:XDC file:12 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D17     [get_ports {vga_green_o[3]}]
set_property src_info {type:XDC file:12 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green_o[*]}]
set_property src_info {type:XDC file:12 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P19     [get_ports vga_hsync_n_o]
set_property src_info {type:XDC file:12 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync_n_o]
set_property src_info {type:XDC file:12 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R19     [get_ports vga_vsync_n_o]
set_property src_info {type:XDC file:12 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync_n_o]
set_property src_info {type:XDC file:13 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W7 [get_ports {disp_segments_n_o[0]}]
set_property src_info {type:XDC file:13 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6 [get_ports {disp_segments_n_o[1]}]
set_property src_info {type:XDC file:13 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U8 [get_ports {disp_segments_n_o[2]}]
set_property src_info {type:XDC file:13 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports {disp_segments_n_o[3]}]
set_property src_info {type:XDC file:13 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5 [get_ports {disp_segments_n_o[4]}]
set_property src_info {type:XDC file:13 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports {disp_segments_n_o[5]}]
set_property src_info {type:XDC file:13 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports {disp_segments_n_o[6]}]
set_property src_info {type:XDC file:13 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports {disp_select_n_o[0]}]
set_property src_info {type:XDC file:13 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports {disp_select_n_o[1]}]
set_property src_info {type:XDC file:13 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports {disp_select_n_o[2]}]
set_property src_info {type:XDC file:13 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W4 [get_ports {disp_select_n_o[3]}]
set_property src_info {type:XDC file:13 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {switches_i[0]}]
set_property src_info {type:XDC file:13 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {switches_i[1]}]
set_property src_info {type:XDC file:13 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {switches_i[2]}]
set_property src_info {type:XDC file:13 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W17 [get_ports {switches_i[3]}]
