# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {Common 17-55}  -new_severity {WARNING} 
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/user/Downloads/CoCiNum/vivado/CoCiNum_LIADI_TRAORE/CoCiNum_LIADI_TRAORE.cache/wt [current_project]
set_property parent.project_path C:/Users/user/Downloads/CoCiNum/vivado/CoCiNum_LIADI_TRAORE/CoCiNum_LIADI_TRAORE.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/user/Downloads/CoCiNum/vivado/CoCiNum_LIADI_TRAORE/CoCiNum_LIADI_TRAORE.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/user/Downloads/CoCiNum/src/vhdl/Counter/CounterModN.vhd
  C:/Users/user/Downloads/CoCiNum/src/vhdl/SegmentDisplay/SegmentDecoder.vhd
  C:/Users/user/Downloads/CoCiNum/vivado/CoCiNum_LIADI_TRAORE/CoCiNum_LIADI_TRAORE.srcs/sources_1/new/taptop.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_Buttons.xdc
set_property used_in_implementation false [get_files C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_Buttons.xdc]

read_xdc C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_Clock.xdc
set_property used_in_implementation false [get_files C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_Clock.xdc]

read_xdc C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_LEDs.xdc
set_property used_in_implementation false [get_files C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_LEDs.xdc]

read_xdc C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_PS2.xdc
set_property used_in_implementation false [get_files C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_PS2.xdc]

read_xdc C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_PmodA.xdc
set_property used_in_implementation false [get_files C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_PmodA.xdc]

read_xdc C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_PmodB.xdc
set_property used_in_implementation false [get_files C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_PmodB.xdc]

read_xdc C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_PmodC.xdc
set_property used_in_implementation false [get_files C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_PmodC.xdc]

read_xdc C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_PmodXADC.xdc
set_property used_in_implementation false [get_files C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_PmodXADC.xdc]

read_xdc C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_SegmentDisplay.xdc
set_property used_in_implementation false [get_files C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_SegmentDisplay.xdc]

read_xdc C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_Switches.xdc
set_property used_in_implementation false [get_files C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_Switches.xdc]

read_xdc C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_UART.xdc
set_property used_in_implementation false [get_files C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_UART.xdc]

read_xdc C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_VGA.xdc
set_property used_in_implementation false [get_files C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_VGA.xdc]

read_xdc C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_td_combinatoire.xdc
set_property used_in_implementation false [get_files C:/Users/user/Downloads/CoCiNum/src/vhdl/Basys3/Basys3_td_combinatoire.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top MicrowaveTop -part xc7a35tcpg236-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MicrowaveTop.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file MicrowaveTop_utilization_synth.rpt -pb MicrowaveTop_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
